version: '3'

services:
  mysql:
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
    image: mariadb:10.1
    ports:
      - 3306:3306
    volumes:
      - ./data/wordpress.sql:/docker-entrypoint-initdb.d/wordpress.sql

  wordpress:
    build:
      context: ./wordpress
    depends_on:
      - mysql
    environment:
      DB_NAME: wordpress
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: mysql
      S3_UPLOADS_BUCKET:
      S3_UPLOADS_KEY:
      S3_UPLOADS_SECRET:
      S3_UPLOADS_REGION:
      S3_UPLOADS_USE_LOCAL: 'true'
      S3_UPLOADS_BUCKET_URL:
      AUTH_KEY: 123
      AUTH_SALT: 123
      LOGGED_IN_KEY: 123
      LOGGED_IN_SALT: 123
      NONCE_KEY: 123
      NONCE_SALT: 123
      SECURE_AUTH_KEY: 123
      SECURE_AUTH_SALT: 123
      WP_DEBUG: 'true'
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content

  react:
    build:
      args:
        SKIP_BUILD: 1
      context: ./react
    command: npm run dev
    depends_on:
      - wordpress
    environment:
      NODE_ENV: development
    volumes:
      - ./react:/usr/src/app
      - /usr/src/app/node_modules

  varnish:
    build:
      context: ./varnish
    depends_on:
      - react
      - wordpress
    ports:
      - 80:80
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
