version: '2'

services:
  react:
    image: REPLACE_ME/react:latest
    environment:
      NODE_ENV: production
    links:
      - wordpress
    mem_limit: 134217728

  wordpress:
    environment:
      DB_NAME: REPLACE_ME
      DB_USER: REPLACE_ME
      DB_PASSWORD: REPLACE_ME
      DB_HOST: REPLACE_ME
      S3_UPLOADS_BUCKET: REPLACE_ME
      S3_UPLOADS_KEY: REPLACE_ME
      S3_UPLOADS_SECRET: REPLACE_ME
      S3_UPLOADS_REGION: REPLACE_ME
      S3_UPLOADS_USE_LOCAL: 'false'
      S3_UPLOADS_BUCKET_URL: REPLACE_ME
      AUTH_KEY: REPLACE_ME
      AUTH_SALT: REPLACE_ME
      LOGGED_IN_KEY: REPLACE_ME
      LOGGED_IN_SALT: REPLACE_ME
      NONCE_KEY: REPLACE_ME
      NONCE_SALT: REPLACE_ME
      SECURE_AUTH_KEY: REPLACE_ME
      SECURE_AUTH_SALT: REPLACE_ME
      WP_DEBUG: 'false'
    image: REPLACE_ME/wordpress:latest
    mem_limit: 402653184

  varnish:
    image: REPLACE_ME/varnish:latest
    links:
      - react
      - wordpress
    mem_limit: 268435456
    ports:
      - 80:80
